### ISSUE TITLE
Text in slider disappears when resizing IE10

### ISSUE THREAD

**Issue by tsilefy** [justinmc/jQuery-Open-Carousel#11] opened 2014-02-24 00:33 UTC
Thanks for this great plugin, Justin!

When using IE10 on Windows 7, any textual element in the sliders disappear whenever the browser is resized, even by a small bit.

To trigger the issue, go to your demo page (http://www.justinmccandless.com/demos/jQuery-Open-Carousel/examples/main/index.html), check the 3rd carousel with the Lorem Ipsum text. Resize the browser (or hit f12 to show the dev tools). The text is gone.

**Comment by justinmc** [comment] 2014-03-05 05:22
Thanks for pointing this out!  I took a quick look at the code and I'm pretty sure I spotted the problem.

The `fullscreen` setting requires a rerender whenever the browser is resized.  We should have only been listening for the resize in fullscreen mode, but we were (uselessly) doing it regardless. Here's the fix I just committed: https://github.com/justinmc/jQuery-Open-Carousel/commit/cb4dd31a67b0f455186c13ded19e71f50a2a076a#diff-0e5915993bf35e9b10f6edaf0a042aa1L208

I don't have a Windows machine right this second to test though, so I'll close the ticket after I take a look on Windows shortly.  I also want to look into the root cause of rerendering causing the text to disappear in IE10.

I've updated the live demo, so you should be able to try it out there.

**Comment by justinmc** [comment] 2014-03-07 05:51
Looks good to me back to IE6.  I'll go ahead and close this ticket, but let me know if you run into further problems.

**Closed as completed by justinmc** 2014-03-07 05:51 UTC

**Comment by tsilefy** [comment] 2014-03-12 05:22
It's perfect! Thanks for being so reactive!
